theme: jekyll-theme-cayman
title: NYC TTP Tech Skills Workshop
description: The NYC Tech Talent Pipeline is working to connect New Yorkers to quality jobs, and deliver quality talent to New York businesses. Using an industry-driven assessment, the Tech Talent Team supports companies in filling entry-level tech roles by surfacing qualified candidates from non-traditional sources across the five boroughs.
