theme: jekyll-theme-cayman
title: NYC TTP Tech Skills Workshop
description: The NYC Tech Talent Pipeline is working to connect New Yorkers to quality jobs, and deliver quality talent to New York business. Using an industry-driven assessment, the Tech Talent Team supports companies in filling entry-level tech roles by surfacing qualified candidates from non-traditional sources across the five boroughs.

Join us for a tech skills workshop designed to help improve your skills and move forward in landing a job. This is an opportunity for you to review the assessment, and learn successful approach and problem solving strategies with the help and guidance of our workshop lead.

After the workshop, you will be invited to retake "Stage 1" of the assessment, and if you pass move along to the next round!
